services:
  - type: web
    name: jobportal-backend
    env: node
    buildCommand: |
      cp package.render.json package.json &&
      npm install --only=production --no-optional --no-audit --no-fund
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
