services:
  - type: web
    name: jobportal-backend
    env: node
    buildCommand: |
      cp package.production.json package.json &&
      npm install &&
      chmod +x node_modules/.bin/* &&
      npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
