services:
  - type: web
    name: jobportal-backend
    env: node
    buildCommand: |
      cp package.production.json package.json &&
      npm install &&
      node_modules/.bin/esbuild server/backend-only.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --out-extension:.js=.mjs
    startCommand: node dist/backend-only.mjs
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
